## Import and Load

In [96]:
import numpy as np
import pandas as pd

In [97]:
df = pd.read_csv("./data/raw.csv", dtype={"Hits": str})

print(f"Loaded dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded dataset: 18979 rows, 77 columns

In [98]:
display(df.head(3))

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

In [99]:
df.iloc[0]["playerUrl"]

'http://sofifa.com/player/158023/lionel-messi/210006/'

In [100]:
print("Columns:", df.columns)

Columns: Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

## Whitespace and Duplicate Cleaning

In [101]:
# removing trailing whitespaces and non-ASCII characters
df.columns = df.columns.str.strip().str.replace(r"[^\x00-\x7F]", "", regex=True)

# inserting an underscore between lowercase and uppercase letters (playerUrl -> player_Url)
df.columns = df.columns.str.replace(r'([a-z])([A-Z])', r'\1 \2', regex=True)

# ensuring the first letter of every column name is in uppercase
df.columns = [col[0].upper() + col[1:] for col in df.columns]

print(df.columns)

Index(['ID', 'Name', 'Long Name', 'Photo Url', 'Player Url', 'Nationality',
       'Age', 'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height',
       'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

In [102]:
print("Duplicates:",df.duplicated().sum())

Duplicates: 0

## Dataset Division Into Info & Stat

In [103]:
df_info = df.loc[:, :"Release Clause"]
df_stat = df.loc[:, "Attacking":]

display(df_info.head(3))
display(df_stat.head(3))

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M

,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,429,85,95,70,91,88,470,96,93,94,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,437,84,95,90,82,86,414,88,81,76,...,High,Low,5 ★,89,93,81,89,35,77,562
2,95,13,11,15,43,13,109,12,13,14,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

## Cleaning `df_info`

In [104]:
df_info.isna().sum()

ID                    0
Name                  0
Long Name             0
Photo Url             0
Player Url            0
Nationality           0
Age                   0
OVA                   0
POT                   0
Club                  0
Contract              0
Positions             0
Height                0
Weight                0
Preferred Foot        0
BOV                   0
Best Position         0
Joined                0
Loan Date End     17966
Value                 0
Wage                  0
Release Clause        0
dtype: int64

### Unstacking Contract

In [105]:
def categorize_contract(contract_str):
    if pd.isna(contract_str):
        return "Unknown"
    elif "On Loan" in contract_str:
        return "On Loan"
    elif "Free" in contract_str:
        return "Free"
    else:
        return "Permanent"
    
df_info["Contract Type"] = df_info["Contract"].apply(categorize_contract)

display(df_info[["Contract", "Contract Type", "Loan Date End"]])

          Contract Contract Type Loan Date End
0      2004 ~ 2021     Permanent           NaN
1      2018 ~ 2022     Permanent           NaN
2      2014 ~ 2023     Permanent           NaN
3      2015 ~ 2023     Permanent           NaN
4      2017 ~ 2022     Permanent           NaN
...            ...           ...           ...
18974  2018 ~ 2022     Permanent           NaN
18975  2020 ~ 2021     Permanent           NaN
18976  2019 ~ 2020     Permanent           NaN
18977  2020 ~ 2022     Permanent           NaN
18978  2019 ~ 2023     Permanent           NaN

[18979 rows x 3 columns]

In [ ]:
def get_contract_year(contract_str, year_idx):
    # year_idx 0 for start, 1 for end
    if pd.isna(contract_str):
        return None
    
    if "~" in str(contract_str):
        year = str(contract_str).split("~")[year_idx].strip()
        return year
    return None

df_info["Contract Start Year"] = df_info["Contract"].apply(get_contract_year, year_idx=0)
df_info["Contract End Year"] = df_info["Contract"].apply(get_contract_year, year_idx=1)

display(df_info[["Contract", "Contract Start Year", "Contract End Year"]].head())

      Contract Contract Start Year Contract End Year
0  2004 ~ 2021                2004              2021
1  2018 ~ 2022                2018              2022
2  2014 ~ 2023                2014              2023
3  2015 ~ 2023                2015              2023
4  2017 ~ 2022                2017              2022

In [107]:
df_info.drop(columns=["Contract"], inplace=True)

In [121]:
first_order = df_info.loc[:, :"Joined"].columns.tolist()
second_order = ["Contract Type", "Contract Start Year", "Contract End Year"]
third_order = df_info.loc[:, "Loan Date End":"Release Clause"].columns.tolist()

df_info = df_info[first_order + second_order + third_order]

In [122]:
df_info.isna().sum()

ID                         0
Name                       0
Long Name                  0
Photo Url                  0
Player Url                 0
Nationality                0
Age                        0
OVA                        0
POT                        0
Club                       0
Positions                  0
Height                     0
Weight                     0
Preferred Foot             0
BOV                        0
Best Position              0
Joined                     0
Contract Type              0
Contract Start Year     1250
Contract End Year       1250
Loan Date End          17966
Value                      0
Wage                       0
Release Clause             0
dtype: int64