## Import and Load

In [105]:
import numpy as np
import pandas as pd

In [106]:
df = pd.read_csv("./data/raw.csv", dtype={"Hits": str})

print(f"Loaded dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded dataset: 18979 rows, 77 columns

In [107]:
display(df.head(3))

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

In [108]:
df.iloc[0]["playerUrl"]

'http://sofifa.com/player/158023/lionel-messi/210006/'

In [109]:
print("Columns:", df.columns)

Columns: Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

## Whitespace and Duplicate Cleaning

In [110]:
# removing trailing whitespaces and non-ASCII characters
df.columns = df.columns.str.strip().str.replace(r"[^\x00-\x7F]", "", regex=True)

# inserting an underscore between lowercase and uppercase letters (playerUrl -> player_Url)
df.columns = df.columns.str.replace(r'([a-z])([A-Z])', r'\1 \2', regex=True)

# ensuring the first letter of every column name is in uppercase
df.columns = [col[0].upper() + col[1:] for col in df.columns]

print(df.columns)

Index(['ID', 'Name', 'Long Name', 'Photo Url', 'Player Url', 'Nationality',
       'Age', 'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height',
       'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

In [111]:
print("Duplicates:",df.duplicated().sum())

Duplicates: 0

## Dataset Division Into Info & Stat

In [112]:
df_info = df.loc[:, :"Release Clause"]
df_stat = df.loc[:, "Attacking":]

display(df_info.head(3))
display(df_stat.head(3))

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M

,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,429,85,95,70,91,88,470,96,93,94,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,437,84,95,90,82,86,414,88,81,76,...,High,Low,5 ★,89,93,81,89,35,77,562
2,95,13,11,15,43,13,109,12,13,14,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

## Cleaning `df_info`

In [113]:
df_info.head(3)

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M

In [114]:
df_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              18979 non-null  int64
 1   Name            18979 non-null  str
 2   Long Name       18979 non-null  str
 3   Photo Url       18979 non-null  str
 4   Player Url      18979 non-null  str
 5   Nationality     18979 non-null  str
 6   Age             18979 non-null  int64
 7   OVA             18979 non-null  int64
 8   POT             18979 non-null  int64
 9   Club            18979 non-null  str
 10  Contract        18979 non-null  str
 11  Positions       18979 non-null  str
 12  Height          18979 non-null  str
 13  Weight          18979 non-null  str
 14  Preferred Foot  18979 non-null  str
 15  BOV             18979 non-null  int64
 16  Best Position   18979 non-null  str
 17  Joined          18979 non-null  str
 18  Loan Date End   1013 non-null   str
 19  Value           18979 non-null  str
 20  Wage            18979 non-null  str
 21  Release Clause  18979 non-null  str
dtypes: int64(5), str(17)
memory usage: 3.2 MB

In [115]:
df_info.isna().sum()

ID                    0
Name                  0
Long Name             0
Photo Url             0
Player Url            0
Nationality           0
Age                   0
OVA                   0
POT                   0
Club                  0
Contract              0
Positions             0
Height                0
Weight                0
Preferred Foot        0
BOV                   0
Best Position         0
Joined                0
Loan Date End     17966
Value                 0
Wage                  0
Release Clause        0
dtype: int64

Things to do:

- Weirdness check strategy for all columns:
    - for `str` types, utilize regex
    - for `int64` types, check `min` and `max` (use `describe`)

- Duplicate check for `ID` column.

- Data type conversions:
    - `Height`, `Weight`, `Value`, `Wage`, `Release Clause` to `float64`
    - `Joined`, `Loan Date End` to `datetime`

- Unstack `Contract`.

### Unstacking `Contract`

In [116]:
def categorize_contract(contract_str):
    if pd.isna(contract_str):
        return "Unknown"
    elif "On Loan" in contract_str:
        return "On Loan"
    elif "Free" in contract_str:
        return "Free"
    else:
        return "Permanent"
    
df_info["Contract Type"] = df_info["Contract"].apply(categorize_contract)

display(df_info[["Contract", "Contract Type", "Loan Date End"]].head(5))

      Contract Contract Type Loan Date End
0  2004 ~ 2021     Permanent           NaN
1  2018 ~ 2022     Permanent           NaN
2  2014 ~ 2023     Permanent           NaN
3  2015 ~ 2023     Permanent           NaN
4  2017 ~ 2022     Permanent           NaN

In [117]:
def get_contract_year(contract_str, year_idx):
    # year_idx 0 for start, 1 for end
    if pd.isna(contract_str):
        return None
    
    if "~" in str(contract_str):
        year = str(contract_str).split("~")[year_idx].strip()
        return year
    return None

df_info["Contract Start Year"] = df_info["Contract"].apply(get_contract_year, year_idx=0)
df_info["Contract End Year"] = df_info["Contract"].apply(get_contract_year, year_idx=1)

display(df_info[["Contract", "Contract Start Year", "Contract End Year"]].head())

      Contract Contract Start Year Contract End Year
0  2004 ~ 2021                2004              2021
1  2018 ~ 2022                2018              2022
2  2014 ~ 2023                2014              2023
3  2015 ~ 2023                2015              2023
4  2017 ~ 2022                2017              2022

In [118]:
df_info.drop(columns=["Contract"], inplace=True)

In [119]:
first_order = df_info.loc[:, :"Joined"].columns.tolist()
second_order = ["Contract Type", "Contract Start Year", "Contract End Year"]
third_order = df_info.loc[:, "Loan Date End":"Release Clause"].columns.tolist()

df_info = df_info[first_order + second_order + third_order]

display(df_info.head(2))

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,BOV,Best Position,Joined,Contract Type,Contract Start Year,Contract End Year,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,93,RW,"Jul 1, 2004",Permanent,2004,2021,NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,92,ST,"Jul 10, 2018",Permanent,2018,2022,NaN,€63M,€220K,€75.9M

### Dropping `Contract Start Year`

In [120]:
joined_contract = df_info[["Joined", "Contract Start Year"]][df_info["Contract Start Year"].notna()]

extracted_year = joined_contract["Joined"].str.extract(r"(?<=,\s)(\d{4})")[0]
condition = (extracted_year == joined_contract["Contract Start Year"])

print("Count of unmatching year of `Joined` and `Contract Start Year` column:", (~condition).sum())

Count of unmatching year of `Joined` and `Contract Start Year` column: 0

This means, `Joined` and `Contract Start Year` are 100% identical across the entire dataset. Due to this, it is redundant to keep both. So, we should drop the `Contract Start Year` column. Why not `Joined`? Because it contains more precise info (the month and the date).

In [121]:
df_info.drop(columns="Contract Start Year", inplace=True)

### Data type conversion

- `Height`, `Weight`, `Value`, `Wage`, `Release Clause` to `float`
- `Joined`, `Loan Date End` to `datetime`

In [122]:
cols_float64 = ["Height", "Weight", "Value", "Wage", "Release Clause"]
cols_datetime = ["Joined", "Loan Date End"]

In [123]:
df_info[cols_float64].head()

  Height Weight    Value   Wage Release Clause
0  170cm   72kg  €103.5M  €560K        €138.4M
1  187cm   83kg     €63M  €220K         €75.9M
2  188cm   87kg    €120M  €125K        €159.4M
3  181cm   70kg    €129M  €370K          €161M
4  175cm   68kg    €132M  €270K        €166.5M

#### `Height` to `float`

In [124]:
height_format_mask = df_info["Height"].str.match(r"\d+cm")
outlier_height = df_info[~height_format_mask]["Height"]

print("Count of values that don't follow the \\d+cm format:", len(outlier_height))

display(outlier_height.head())

Count of values that don't follow the \d+cm format: 40

793     6'2"
847     6'3"
848     6'5"
860    5'11"
861     6'4"
Name: Height, dtype: str

In [125]:
print("Count of outliers matching the \\d+\'\\d+\" format:", df_info["Height"].str.match(r"\d+\'\d+\"").sum())

Count of outliers matching the \d+'\d+" format: 40

Because the above print value 40 is equal to the length of the total outlier formats, we can say all the outliers follow the same format which is `\d+'\d+"` (in feet and inches rather than centimeters).

In [126]:
def to_cm_float(height_str: str):
    if pd.isna(height_str):
        return pd.NA
    
    height_str = height_str.strip().lower()
    
    if "'" in height_str:
        foot, inch = height_str.split("'")

        foot = float(foot)
        inch = float(inch.replace('"', ''))

        total_inch = (foot * 12) + inch

        return round(total_inch * 2.54, 2)
    
    elif "cm" in height_str:
        return round(float(height_str.replace("cm", "")), 2)
    
    else:
        return float(height_str)

df_info["Height"] = df_info["Height"].apply(to_cm_float)

df_info["Height"].head()

0    170.0
1    187.0
2    188.0
3    181.0
4    175.0
Name: Height, dtype: float64

#### `Weight` to `float`

In [127]:
weight_format_mask = df_info["Weight"].str.match(r"\d+kg")
outlier_weight = df_info[~weight_format_mask]["Weight"]

print("Count of values that don't follow the \\d+kg format:", len(outlier_weight))

display(outlier_weight.head())

Count of values that don't follow the \d+kg format: 40

793    183lbs
847    179lbs
848    183lbs
860    172lbs
861    196lbs
Name: Weight, dtype: str

In [128]:
print("Count of outliers matching the \\d+lbs format:", len(outlier_weight.str.match(r"\d+lbs")))

Count of outliers matching the \d+lbs format: 40

All the weight outliers follow the `\d+lbs` format (in pound rather than kilograms).

In [129]:
def to_kg_float(weight_str: str):
    if pd.isna(weight_str):
        return pd.NA
    
    weight_str = weight_str.strip()

    if "lbs" in weight_str:
        pound = float(weight_str.replace("lbs", ""))
        return round(pound * 0.454, 2)
    
    elif "kg" in weight_str:
        return round(float(weight_str.replace("kg", "")), 2)
    
    else:
        return float(weight_str)
    
df_info["Weight"] = df_info["Weight"].apply(to_kg_float)

df_info["Weight"].head()

0    72.0
1    83.0
2    87.0
3    70.0
4    68.0
Name: Weight, dtype: float64