## Import and Load

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("./data/raw.csv", dtype={"Hits": str})

print(f"Loaded dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded dataset: 18979 rows, 77 columns

In [4]:
display(df.head(3))

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

In [5]:
print("Columns:", df.columns)

Columns: Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

## Whitespace and Duplicate Cleaning

In [6]:
# removing trailing whitespaces and non-ASCII characters
df.columns = df.columns.str.strip().str.replace(r"[^\x00-\x7F]", "", regex=True)

# inserting a space between lowercase and uppercase letters (playerUrl -> player Url)
df.columns = df.columns.str.replace(r'([a-z])([A-Z])', r'\1 \2', regex=True)

# ensuring the first letter of every column name is in uppercase
df.columns = [col[0].upper() + col[1:] for col in df.columns]

print(df.columns)

Index(['ID', 'Name', 'Long Name', 'Photo Url', 'Player Url', 'Nationality',
       'Age', 'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height',
       'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W',
       'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

In [7]:
print("Duplicates:",df.duplicated().sum())

Duplicates: 0

## Dataset Division Into Info & Stat

In [8]:
df_info = df.loc[:, :"Release Clause"]
df_stat = df.loc[:, "Attacking":]

display(df_info.head(3))
display(df_stat.head(3))

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M

,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,429,85,95,70,91,88,470,96,93,94,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,437,84,95,90,82,86,414,88,81,76,...,High,Low,5 ★,89,93,81,89,35,77,562
2,95,13,11,15,43,13,109,12,13,14,...,Medium,Medium,3 ★,87,92,78,90,52,90,150

## Cleaning `df_info`

In [9]:
df_info.head(3)

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M

In [10]:
df_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              18979 non-null  int64
 1   Name            18979 non-null  str
 2   Long Name       18979 non-null  str
 3   Photo Url       18979 non-null  str
 4   Player Url      18979 non-null  str
 5   Nationality     18979 non-null  str
 6   Age             18979 non-null  int64
 7   OVA             18979 non-null  int64
 8   POT             18979 non-null  int64
 9   Club            18979 non-null  str
 10  Contract        18979 non-null  str
 11  Positions       18979 non-null  str
 12  Height          18979 non-null  str
 13  Weight          18979 non-null  str
 14  Preferred Foot  18979 non-null  str
 15  BOV             18979 non-null  int64
 16  Best Position   18979 non-null  str
 17  Joined          18979 non-null  str
 18  Loan Date End   1013 non-null   str
 19  Value           18979 non-null  str
 20  Wage            18979 non-null  str
 21  Release Clause  18979 non-null  str
dtypes: int64(5), str(17)
memory usage: 3.2 MB

In [11]:
df_info.isna().sum()

ID                    0
Name                  0
Long Name             0
Photo Url             0
Player Url            0
Nationality           0
Age                   0
OVA                   0
POT                   0
Club                  0
Contract              0
Positions             0
Height                0
Weight                0
Preferred Foot        0
BOV                   0
Best Position         0
Joined                0
Loan Date End     17966
Value                 0
Wage                  0
Release Clause        0
dtype: int64

Things to do:

- Weirdness check strategy for all columns:
    - for `str` types, utilize regex
    - for `int64` types, check `min` and `max` (use `describe`)

- Duplicate check for `ID` column.

- Data type conversions:
    - `Height`, `Weight`, `Value`, `Wage`, `Release Clause` to `float64`
    - `Joined`, `Loan Date End` to `datetime`

- Unstack `Contract`.

### Unstacking `Contract`

In [12]:
def categorize_contract(contract_str):
    if pd.isna(contract_str):
        return "Unknown"
    elif "On Loan" in contract_str:
        return "On Loan"
    elif "Free" in contract_str:
        return "Free"
    else:
        return "Permanent"
    
df_info["Contract Type"] = df_info["Contract"].apply(categorize_contract)

display(df_info[["Contract", "Contract Type", "Loan Date End"]].head())

      Contract Contract Type Loan Date End
0  2004 ~ 2021     Permanent           NaN
1  2018 ~ 2022     Permanent           NaN
2  2014 ~ 2023     Permanent           NaN
3  2015 ~ 2023     Permanent           NaN
4  2017 ~ 2022     Permanent           NaN

In [13]:
def get_contract_year(contract_str, year_idx):
    # year_idx 0 for start, 1 for end
    if pd.isna(contract_str):
        return None
    
    if "~" in str(contract_str):
        year = str(contract_str).split("~")[year_idx].strip()
        return year
    return None

df_info["Contract Start Year"] = df_info["Contract"].apply(get_contract_year, year_idx=0)
df_info["Contract End Year"] = df_info["Contract"].apply(get_contract_year, year_idx=1)

display(df_info[["Contract", "Contract Start Year", "Contract End Year"]].head())

      Contract Contract Start Year Contract End Year
0  2004 ~ 2021                2004              2021
1  2018 ~ 2022                2018              2022
2  2014 ~ 2023                2014              2023
3  2015 ~ 2023                2015              2023
4  2017 ~ 2022                2017              2022

In [14]:
df_info.drop(columns=["Contract"], inplace=True)

In [15]:
first_order = df_info.loc[:, :"Joined"].columns.tolist()
second_order = ["Contract Type", "Contract Start Year", "Contract End Year"]
third_order = df_info.loc[:, "Loan Date End":"Release Clause"].columns.tolist()

df_info = df_info[first_order + second_order + third_order]

display(df_info.head(2))

,ID,Name,Long Name,Photo Url,Player Url,Nationality,Age,OVA,POT,Club,...,BOV,Best Position,Joined,Contract Type,Contract Start Year,Contract End Year,Loan Date End,Value,Wage,Release Clause
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,93,RW,"Jul 1, 2004",Permanent,2004,2021,NaN,€103.5M,€560K,€138.4M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,92,ST,"Jul 10, 2018",Permanent,2018,2022,NaN,€63M,€220K,€75.9M

### Dropping `Contract Start Year`

In [16]:
joined_contract = df_info[["Joined", "Contract Start Year"]][df_info["Contract Start Year"].notna()]

extracted_year = joined_contract["Joined"].str.extract(r"(?<=,\s)(\d{4})")[0]
condition = (extracted_year == joined_contract["Contract Start Year"])

print("Count of unmatching year of `Joined` and `Contract Start Year` column:", (~condition).sum())

Count of unmatching year of `Joined` and `Contract Start Year` column: 0

This means, `Joined` and `Contract Start Year` are 100% identical across the entire dataset. Due to this, it is redundant to keep both. So, we should drop the `Contract Start Year` column. Why not `Joined`? Because it contains more precise info (the month and the date).

In [17]:
df_info.drop(columns="Contract Start Year", inplace=True)

### Data type conversion

- `Height`, `Weight`, `Value`, `Wage`, `Release Clause` to `float`
- `Joined`, `Loan Date End` to `datetime`

In [18]:
cols_float64 = ["Height", "Weight", "Value", "Wage", "Release Clause"]
cols_datetime = ["Joined", "Loan Date End"]

In [19]:
df_info[cols_float64].head()

  Height Weight    Value   Wage Release Clause
0  170cm   72kg  €103.5M  €560K        €138.4M
1  187cm   83kg     €63M  €220K         €75.9M
2  188cm   87kg    €120M  €125K        €159.4M
3  181cm   70kg    €129M  €370K          €161M
4  175cm   68kg    €132M  €270K        €166.5M

#### `Height` to `float`

In [20]:
height_format_mask = df_info["Height"].str.match(r"\d+cm")
outlier_height = df_info[~height_format_mask]["Height"]

print("Count of values that don't follow the \\d+cm format:", len(outlier_height))

display(outlier_height.head())

Count of values that don't follow the \d+cm format: 40

793     6'2"
847     6'3"
848     6'5"
860    5'11"
861     6'4"
Name: Height, dtype: str

In [21]:
print("Count of outliers matching the \\d+\'\\d+\" format:", df_info["Height"].str.match(r"\d+\'\d+\"").sum())

Count of outliers matching the \d+'\d+" format: 40

Because the above print value 40 is equal to the length of the total outlier formats, we can say all the outliers follow the same format which is `\d+'\d+"` (in feet and inches rather than centimeters).

In [22]:
def to_cm_float(height_str: str):
    if pd.isna(height_str):
        return pd.NA
    
    height_str = height_str.strip().lower()
    
    if "'" in height_str:
        foot, inch = height_str.split("'")

        foot = float(foot)
        inch = float(inch.replace('"', ''))

        total_inch = (foot * 12) + inch

        return round(total_inch * 2.54, 2)
    
    elif "cm" in height_str:
        return round(float(height_str.replace("cm", "")), 2)
    
    else:
        return float(height_str)

df_info["Height"] = df_info["Height"].apply(to_cm_float)

df_info["Height"].head()

0    170.0
1    187.0
2    188.0
3    181.0
4    175.0
Name: Height, dtype: float64

#### `Weight` to `float`

In [23]:
weight_format_mask = df_info["Weight"].str.match(r"\d+kg")
outlier_weight = df_info[~weight_format_mask]["Weight"]

print("Count of values that don't follow the \\d+kg format:", len(outlier_weight))

display(outlier_weight.head())

Count of values that don't follow the \d+kg format: 40

793    183lbs
847    179lbs
848    183lbs
860    172lbs
861    196lbs
Name: Weight, dtype: str

In [24]:
print("Count of outliers matching the \\d+lbs format:", len(outlier_weight.str.match(r"\d+lbs")))

Count of outliers matching the \d+lbs format: 40

All the weight outliers follow the `\d+lbs` format (in pound rather than kilograms).

In [25]:
def to_kg_float(weight_str: str):
    if pd.isna(weight_str):
        return pd.NA
    
    weight_str = weight_str.strip()

    if "lbs" in weight_str:
        pound = float(weight_str.replace("lbs", ""))
        return round(pound * 0.454, 2)
    
    elif "kg" in weight_str:
        return round(float(weight_str.replace("kg", "")), 2)
    
    else:
        return float(weight_str)
    
df_info["Weight"] = df_info["Weight"].apply(to_kg_float)

df_info["Weight"].head()

0    72.0
1    83.0
2    87.0
3    70.0
4    68.0
Name: Weight, dtype: float64

#### `Value`, `Wage`, `Release Clause` to `float`

In [26]:
value_format_mask = df_info["Value"].str.match(r"€\d+(?:\.\d+)?[KM]")
wage_format_mask = df_info["Wage"].str.match(r"€\d+(?:\.\d+)?[KM]")
clause_format_mask = df_info["Release Clause"].str.match(r"€\d+(?:\.\d+)?[KM]")

outlier_value = df_info[~value_format_mask]["Value"]
outlier_wage = df_info[~wage_format_mask]["Wage"]
outlier_clause = df_info[~clause_format_mask]["Release Clause"]

print("Count of values that don't follow the €\\d+(?:\\.\\d+)?[KM] format:")
print("\tValue:", len(outlier_value))
print("\tWage:", len(outlier_wage))
print("\tRelease Clause:", len(outlier_clause))

display(outlier_value.head(2))
display(outlier_wage.head(2))
display(outlier_clause.head(2))

display(outlier_value.tail(2))
display(outlier_wage.tail(2))
display(outlier_clause.tail(2))

Count of values that don't follow the €\d+(?:\.\d+)?[KM] format:
	Value: 248
	Wage: 3950
	Release Clause: 1261

289    €0
292    €0
Name: Value, dtype: str

289    €0
292    €0
Name: Wage, dtype: str

205    €0
248    €0
Name: Release Clause, dtype: str

17661    €0
18205    €0
Name: Value, dtype: str

18975    €500
18976    €500
Name: Wage, dtype: str

18622    €0
18680    €0
Name: Release Clause, dtype: str

In [27]:
print(outlier_value.unique())
print(outlier_wage.unique())
print(outlier_clause.unique())

<StringArray>
['€0']
Length: 1, dtype: str
<StringArray>
[  '€0', '€900', '€850', '€500', '€700', '€950', '€750', '€650', '€600',
 '€800', '€550']
Length: 11, dtype: str
<StringArray>
['€0']
Length: 1, dtype: str

In [28]:
def to_million_float(value_str: str):
    if pd.isna(value_str):
        return pd.NA
    
    value_str = value_str.strip().replace("€", "")

    if "M" in value_str:
        value_float = float(value_str.replace("M", "")) * 10e6
        return value_float
    
    elif "K" in value_str:
        value_float = float(value_str.replace("K", "")) * 10e3
        return value_float

    else:
        return float(value_str)
    
df_info["Value"] = df_info["Value"].apply(to_million_float)
df_info["Wage"] = df_info["Wage"].apply(to_million_float)
df_info["Release Clause"] = df_info["Release Clause"].apply(to_million_float)

display(df_info["Value"].head())
display(df_info["Wage"].head())
display(df_info["Release Clause"].head())

0    1.035000e+09
1    6.300000e+08
2    1.200000e+09
3    1.290000e+09
4    1.320000e+09
Name: Value, dtype: float64

0    5600000.0
1    2200000.0
2    1250000.0
3    3700000.0
4    2700000.0
Name: Wage, dtype: float64

0    1.384000e+09
1    7.590000e+08
2    1.594000e+09
3    1.610000e+09
4    1.665000e+09
Name: Release Clause, dtype: float64

In [29]:
df_info.describe()[["Value", "Wage", "Release Clause"]]

              Value          Wage  Release Clause
count  1.897900e+04  1.897900e+04    1.897900e+04
mean   2.865063e+07  8.984310e+04    3.962951e+07
std    7.685154e+07  1.975443e+05    9.772762e+07
min    0.000000e+00  0.000000e+00    0.000000e+00
25%    4.750000e+06  1.000000e+04    4.235000e+06
50%    9.500000e+06  3.000000e+04    1.000000e+07
75%    2.000000e+07  8.000000e+04    2.800000e+07
max    1.855000e+09  5.600000e+06    2.031000e+09

#### `Joined`, `Loan Date End` to `datetime`

In [30]:
cols_to_datetime = ["Joined", "Loan Date End"]
df_info[cols_to_datetime] = df_info[cols_to_datetime].apply(pd.to_datetime, errors="coerce")

df_info[["Joined", "Loan Date End"]].head()

      Joined Loan Date End
0 2004-07-01           NaT
1 2018-07-10           NaT
2 2014-07-16           NaT
3 2015-08-30           NaT
4 2017-08-03           NaT

In [31]:
df_info[df_info["Loan Date End"].notna()]["Loan Date End"]

205     2021-06-30
248     2021-06-30
254     2021-06-30
302     2021-06-30
306     2021-06-30
           ...
18472   2021-08-31
18571   2021-06-30
18600   2020-12-31
18622   2020-12-31
18680   2020-12-31
Name: Loan Date End, Length: 1013, dtype: datetime64[us]

#### `Contract End Year` to `int`

In [32]:
df_info["Contract End Year"] = df_info["Contract End Year"].astype("Int64")

df_info["Contract End Year"].head()

0    2021
1    2022
2    2023
3    2023
4    2022
Name: Contract End Year, dtype: Int64

### Is/With/Without `ID` Duplicates

In [37]:
print("Total duplicates:", df_info.duplicated().sum())
print("Duplicate IDs:", df_info["ID"].duplicated().sum())
print("Duplicate rows excluding ID:", df_info.drop(columns=["ID"]).duplicated().sum())

Total duplicates: 0
Duplicate IDs: 0
Duplicate rows excluding ID: 0

### String columns

#### Unnecessary whitespaces

In [46]:
str_cols = df_info.select_dtypes(include=['object', 'string']).columns.tolist()
print(f"String columns ({len(str_cols)}):", str_cols)

String columns (10): ['Name', 'Long Name', 'Photo Url', 'Player Url', 'Nationality', 'Club', 'Positions', 'Preferred Foot', 'Best Position', 'Contract Type']

In [49]:
for col in str_cols:
    df_info.loc[:, col] = df_info.loc[:, col].str.strip().str.replace(r"\s+", " ", regex=True)

In [51]:
df_info[str_cols].head(3)

,Name,Long Name,Photo Url,Player Url,Nationality,Club,Positions,Preferred Foot,Best Position,Contract Type
0,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,FC Barcelona,"RW, ST, CF",Left,RW,Permanent
1,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,Juventus,"ST, LW",Right,ST,Permanent
2,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,Atlético Madrid,GK,Right,GK,Permanent

#### Sanity check

In [55]:
photo_url_mask = df_info["Photo Url"].str.match(r"https:\/\/cdn.sofifa.com\/players\/\d+\/\d+\/\w+\.png")
player_url_mask = df_info["Player Url"].str.match(r"http:\/\/sofifa.com\/player\/\d+\/[a-zA-Z-]+\/\d+/")

print("Anomaly photo urls:", (~photo_url_mask).sum())
print("Anomaly player urls:", (~player_url_mask).sum())

Anomaly photo urls: 0
Anomaly player urls: 0

This is getting so overwhelming, so I'll assume the entered data are correct.

### Conclusion

In [56]:
df_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 18979 non-null  int64
 1   Name               18979 non-null  str
 2   Long Name          18979 non-null  str
 3   Photo Url          18979 non-null  str
 4   Player Url         18979 non-null  str
 5   Nationality        18979 non-null  str
 6   Age                18979 non-null  int64
 7   OVA                18979 non-null  int64
 8   POT                18979 non-null  int64
 9   Club               18979 non-null  str
 10  Positions          18979 non-null  str
 11  Height             18979 non-null  float64
 12  Weight             18979 non-null  float64
 13  Preferred Foot     18979 non-null  str
 14  BOV                18979 non-null  int64
 15  Best Position      18979 non-null  str
 16  Joined             18979 non-null  datetime64[us]
 17  Contract Type      18979 non-null  str
 18  Contract End Year  17729 non-null  Int64
 19  Loan Date End      1013 non-null   datetime64[us]
 20  Value              18979 non-null  float64
 21  Wage               18979 non-null  float64
 22  Release Clause     18979 non-null  float64
dtypes: Int64(1), datetime64[us](2), float64(5), int64(5), str(10)
memory usage: 3.3 MB

In [57]:
df_info.describe()

,ID,Age,OVA,POT,Height,Weight,BOV,Joined,Contract End Year,Loan Date End,Value,Wage,Release Clause
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979,17729.0,1013,1.897900e+04,1.897900e+04,1.897900e+04
mean,226403.384794,25.194109,65.718636,71.136414,181.200409,75.019275,66.751726,2018-09-13 10:27:42.005374,2022.064414,2021-06-13 23:44:21.796643,2.865063e+07,8.984310e+04,3.962951e+07
min,41.000000,16.000000,47.000000,47.000000,155.000000,50.000000,48.000000,1998-01-01 00:00:00,2020.0,2020-11-22 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00
25%,210135.000000,21.000000,61.000000,67.000000,176.000000,70.000000,62.000000,2018-01-08 12:00:00,2021.0,2021-06-30 00:00:00,4.750000e+06,1.000000e+04,4.235000e+06
50%,232418.000000,25.000000,66.000000,71.000000,181.000000,75.000000,67.000000,2019-06-25 00:00:00,2022.0,2021-06-30 00:00:00,9.500000e+06,3.000000e+04,1.000000e+07
75%,246922.500000,29.000000,70.000000,75.000000,186.000000,80.000000,71.000000,2020-01-17 00:00:00,2023.0,2021-06-30 00:00:00,2.000000e+07,8.000000e+04,2.800000e+07
max,259216.000000,53.000000,93.000000,95.000000,206.000000,110.000000,93.000000,2020-10-08 00:00:00,2028.0,2023-06-30 00:00:00,1.855000e+09,5.600000e+06,2.031000e+09
std,27141.054157,4.710520,6.968999,6.114635,6.840192,7.073614,6.747193,NaN,1.276312,NaN,7.685154e+07,1.975443e+05,9.772762e+07

In [60]:
df_info.isna().sum()

ID                       0
Name                     0
Long Name                0
Photo Url                0
Player Url               0
Nationality              0
Age                      0
OVA                      0
POT                      0
Club                     0
Positions                0
Height                   0
Weight                   0
Preferred Foot           0
BOV                      0
Best Position            0
Joined                   0
Contract Type            0
Contract End Year     1250
Loan Date End        17966
Value                    0
Wage                     0
Release Clause           0
dtype: int64

## Cleaning `df_stat`

In [59]:
df_stat.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 55 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Attacking         18979 non-null  int64
 1   Crossing          18979 non-null  int64
 2   Finishing         18979 non-null  int64
 3   Heading Accuracy  18979 non-null  int64
 4   Short Passing     18979 non-null  int64
 5   Volleys           18979 non-null  int64
 6   Skill             18979 non-null  int64
 7   Dribbling         18979 non-null  int64
 8   Curve             18979 non-null  int64
 9   FK Accuracy       18979 non-null  int64
 10  Long Passing      18979 non-null  int64
 11  Ball Control      18979 non-null  int64
 12  Movement          18979 non-null  int64
 13  Acceleration      18979 non-null  int64
 14  Sprint Speed      18979 non-null  int64
 15  Agility           18979 non-null  int64
 16  Reactions         18979 non-null  int64
 17  Balance           18979 non-null  int64
 18  Power             18979 non-null  int64
 19  Shot Power        18979 non-null  int64
 20  Jumping           18979 non-null  int64
 21  Stamina           18979 non-null  int64
 22  Strength          18979 non-null  int64
 23  Long Shots        18979 non-null  int64
 24  Mentality         18979 non-null  int64
 25  Aggression        18979 non-null  int64
 26  Interceptions     18979 non-null  int64
 27  Positioning       18979 non-null  int64
 28  Vision            18979 non-null  int64
 29  Penalties         18979 non-null  int64
 30  Composure         18979 non-null  int64
 31  Defending         18979 non-null  int64
 32  Marking           18979 non-null  int64
 33  Standing Tackle   18979 non-null  int64
 34  Sliding Tackle    18979 non-null  int64
 35  Goalkeeping       18979 non-null  int64
 36  GK Diving         18979 non-null  int64
 37  GK Handling       18979 non-null  int64
 38  GK Kicking        18979 non-null  int64
 39  GK Positioning    18979 non-null  int64
 40  GK Reflexes       18979 non-null  int64
 41  Total Stats       18979 non-null  int64
 42  Base Stats        18979 non-null  int64
 43  W/F               18979 non-null  str
 44  SM                18979 non-null  str
 45  A/W               18979 non-null  str
 46  D/W               18979 non-null  str
 47  IR                18979 non-null  str
 48  PAC               18979 non-null  int64
 49  SHO               18979 non-null  int64
 50  PAS               18979 non-null  int64
 51  DRI               18979 non-null  int64
 52  DEF               18979 non-null  int64
 53  PHY               18979 non-null  int64
 54  Hits              16384 non-null  str
dtypes: int64(49), str(6)
memory usage: 8.0 MB